/**
 * Internationalization (i18n) Module
 * Manages translations for different languages
 */

const translations = {
	en: {
		// Headers and Titles
		projectDocumentation: name => `${name} Documentation`,
		generated: 'Generated',
		profile: 'Profile',
		system: 'System',
		trigger: 'Trigger',

		// Table of Contents
		tableOfContents: 'Table of Contents',
		systemOverview: 'System Overview',
		adapterInstances: 'Adapter Instances',
		manualInformation: 'Manual Information',
		appendices: 'Appendices',

		// System Chapter
		projectInformation: 'Project Information',
		projectName: 'Project Name',
		targetSystem: 'Target System',
		primaryHost: 'Primary Host',
		name: 'Name',
		platform: 'Platform',
		version: 'Version',
		systemStatistics: 'System Statistics',
		totalAdapterInstances: 'Total Adapter Instances',
		enabledInstances: 'Enabled Instances',
		disabledInstances: 'Disabled Instances',
		totalStateObjects: 'Total State Objects',
		writableStates: 'Writable States',
		readOnlyStates: 'Read-only States',
		hosts: 'Hosts',

		// Rooms Chapter
		roomsAndFunctions: 'Rooms & Functions',
		rooms: 'Rooms',
		functions: 'Functions',
		totalRooms: 'Total Rooms',
		totalFunctions: 'Total Functions',
		memberCount: 'Devices / Datapoints',
		noRoomsDefined: 'No rooms defined yet.',

		// Scripts Chapter
		scripts: 'Scripts',
		totalScripts: 'Total Scripts',
		enabledScripts: 'Active Scripts',
		disabledScripts: 'Inactive Scripts',
		scriptName: 'Name',
		scriptFolder: 'Folder',
		scriptStatus: 'Status',
		scriptTrigger: 'Trigger',
		scriptDescription: 'Description',
		noScriptsDefined: 'No scripts found (script adapter may not be installed).',
		active: 'active',
		inactive: 'inactive',

		// Maintenance Chapter
		maintenance: 'Maintenance & Diagnostics',
		maintenanceChecklist: 'Documentation Checklist',
		documentationScore: 'Documentation Score',
		instancesWithoutRoom: 'Instances without room assignment',
		scriptsWithoutDescription: 'Scripts without description',
		disabledInstancesHint: 'Disabled instances',
		allGood: 'Everything looks good.',
		checkOk: 'OK',
		checkIssue: 'Needs attention',

		// Adapters Chapter
		overview: 'Overview',
		totalAdapters: 'Total Adapters',
		totalInstances: 'Total Instances',
		adapterDetails: 'Adapter Details',
		instanceDetails: 'Instance Details',
		enabled: 'enabled',
		disabled: 'disabled',

		// Manual Context
		description: 'Description',
		contact: 'Contact',
		additionalNotes: 'Additional Notes',

		// Appendices
		stateObjectsSummary: 'State Objects Summary',
		total: 'Total',
		writable: 'Writable',
		readOnly: 'Read-only',
		collectionInformation: 'Collection Information',
		collectedAt: 'Collected at',
		schemaVersion: 'Schema Version',
		generatedBy: 'Generated by ioBroker.autodoc v',
	},
	de: {
		// Headers and Titles
		projectDocumentation: name => `${name} Dokumentation`,
		generated: 'Generiert',
		profile: 'Profil',
		system: 'System',
		trigger: 'Auslöser',

		// Table of Contents
		tableOfContents: 'Inhaltsverzeichnis',
		systemOverview: 'Systemübersicht',
		adapterInstances: 'Adapter-Instanzen',
		manualInformation: 'Manuelle Informationen',
		appendices: 'Anhänge',

		// System Chapter
		projectInformation: 'Projektinformationen',
		projectName: 'Projektname',
		targetSystem: 'Zielsystem',
		primaryHost: 'Primärer Host',
		name: 'Name',
		platform: 'Plattform',
		version: 'Version',
		systemStatistics: 'Systemstatistiken',
		totalAdapterInstances: 'Gesamt Adapter-Instanzen',
		enabledInstances: 'Aktivierte Instanzen',
		disabledInstances: 'Deaktivierte Instanzen',
		totalStateObjects: 'Gesamt State-Objekte',
		writableStates: 'Schreibbare States',
		readOnlyStates: 'Nur lesbare States',
		hosts: 'Hosts',

		// Rooms Chapter
		roomsAndFunctions: 'Räume & Funktionen',
		rooms: 'Räume',
		functions: 'Funktionen',
		totalRooms: 'Gesamt Räume',
		totalFunctions: 'Gesamt Funktionen',
		memberCount: 'Geräte / Datenpunkte',
		noRoomsDefined: 'Noch keine Räume definiert.',

		// Scripts Chapter
		scripts: 'Skripte',
		totalScripts: 'Gesamt Skripte',
		enabledScripts: 'Aktive Skripte',
		disabledScripts: 'Inaktive Skripte',
		scriptName: 'Name',
		scriptFolder: 'Ordner',
		scriptStatus: 'Status',
		scriptTrigger: 'Auslöser',
		scriptDescription: 'Beschreibung',
		noScriptsDefined: 'Keine Skripte gefunden (Script-Adapter möglicherweise nicht installiert).',
		active: 'aktiv',
		inactive: 'inaktiv',

		// Maintenance Chapter
		maintenance: 'Wartung & Diagnose',
		maintenanceChecklist: 'Dokumentations-Checkliste',
		documentationScore: 'Dokumentations-Score',
		instancesWithoutRoom: 'Instanzen ohne Raumzuweisung',
		scriptsWithoutDescription: 'Skripte ohne Beschreibung',
		disabledInstancesHint: 'Deaktivierte Instanzen',
		allGood: 'Alles sieht gut aus.',
		checkOk: 'OK',
		checkIssue: 'Handlungsbedarf',

		// Adapters Chapter
		overview: 'Übersicht',
		totalAdapters: 'Gesamt Adapter',
		totalInstances: 'Gesamt Instanzen',
		adapterDetails: 'Adapter-Details',
		instanceDetails: 'Instanz-Details',
		enabled: 'aktiviert',
		disabled: 'deaktiviert',

		// Manual Context
		description: 'Beschreibung',
		contact: 'Kontakt',
		additionalNotes: 'Zusätzliche Hinweise',

		// Appendices
		stateObjectsSummary: 'State-Objekte Zusammenfassung',
		total: 'Gesamt',
		writable: 'Schreibbar',
		readOnly: 'Nur lesbar',
		collectionInformation: 'Erfassungsinformationen',
		collectedAt: 'Erfasst am',
		schemaVersion: 'Schema-Version',
		generatedBy: 'Generiert von ioBroker.autodoc v',
	},
	fr: {
		projectDocumentation: name => `Documentation ${name}`,
		generated: 'Généré',
		profile: 'Profil',
		system: 'Système',
		trigger: 'Déclencheur',
		tableOfContents: 'Table des matières',
		systemOverview: 'Aperçu du système',
		adapterInstances: "Instances d'adaptateurs",
		manualInformation: 'Informations manuelles',
		appendices: 'Appendices',
		projectInformation: 'Informations du projet',
		projectName: 'Nom du projet',
		targetSystem: 'Système cible',
		primaryHost: 'Hôte principal',
		name: 'Nom',
		platform: 'Plateforme',
		version: 'Version',
		systemStatistics: 'Statistiques du système',
		totalAdapterInstances: "Nombre total d'instances d'adaptateurs",
		enabledInstances: 'Instances activées',
		disabledInstances: 'Instances désactivées',
		totalStateObjects: "Nombre total d'objets d'état",
		writableStates: 'États inscriptibles',
		readOnlyStates: 'États en lecture seule',
		hosts: 'Hôtes',
		// Rooms Chapter
		roomsAndFunctions: 'Pièces & Fonctions',
		rooms: 'Pièces',
		functions: 'Fonctions',
		totalRooms: 'Total des pièces',
		totalFunctions: 'Total des fonctions',
		memberCount: 'Appareils / Points de données',
		noRoomsDefined: "Aucune pièce définie pour l'instant.",

		// Scripts Chapter
		scripts: 'Scripts',
		totalScripts: 'Total des scripts',
		enabledScripts: 'Scripts actifs',
		disabledScripts: 'Scripts inactifs',
		scriptName: 'Nom',
		scriptFolder: 'Dossier',
		scriptStatus: 'Statut',
		scriptTrigger: 'Déclencheur',
		scriptDescription: 'Description',
		noScriptsDefined: "Aucun script trouvé (l'adaptateur script n'est peut-être pas installé).",
		active: 'actif',
		inactive: 'inactif',

		// Maintenance Chapter
		maintenance: 'Maintenance & Diagnostics',
		maintenanceChecklist: 'Liste de contrôle de documentation',
		documentationScore: 'Score de documentation',
		instancesWithoutRoom: 'Instances sans pièce assignée',
		scriptsWithoutDescription: 'Scripts sans description',
		disabledInstancesHint: 'Instances désactivées',
		allGood: 'Tout semble bon.',
		checkOk: 'OK',
		checkIssue: 'À corriger',

		overview: 'Aperçu',
		totalAdapters: "Nombre total d'adaptateurs",
		totalInstances: "Nombre total d'instances",
		adapterDetails: "Détails de l'adaptateur",
		instanceDetails: "Détails de l'instance",
		enabled: 'activé',
		disabled: 'désactivé',
		description: 'Description',
		contact: 'Contact',
		additionalNotes: 'Notes supplémentaires',
		stateObjectsSummary: "Résumé des objets d'état",
		total: 'Total',
		writable: 'Inscriptible',
		readOnly: 'Lecture seule',
		collectionInformation: 'Informations de collecte',
		collectedAt: 'Collecté à',
		schemaVersion: 'Version du schéma',
		generatedBy: 'Généré par ioBroker.autodoc v',
	},
};

/**
 * Internationalization helper for AutoDoc translations.
 */
class I18n {
	/**
	 * Initialize with default language.
	 */
	constructor() {
		this.currentLanguage = 'en';
	}

	/**
	 * Set the current language for translations
	 *
	 * @param {string} lang Language code (e.g., 'en', 'de', 'fr')
	 */
	setLanguage(lang) {
		if (translations[lang]) {
			this.currentLanguage = lang;
		} else {
			// Fallback to English if language not found
			this.currentLanguage = 'en';
		}
	}

	/**
	 * Get a translated string
	 *
	 * @param {string} key Translation key
	 * @param {*} args Optional arguments for template functions
	 * @returns {string} Translated string or key if not found
	 */
	t(key, ...args) {
		const lang = translations[this.currentLanguage];
		if (!lang || !lang[key]) {
			// Fallback to English
			const enLang = translations.en;
			if (enLang[key]) {
				const value = enLang[key];
				return typeof value === 'function' ? value(...args) : value;
			}
			return key;
		}

		const value = lang[key];
		return typeof value === 'function' ? value(...args) : value;
	}

	/**
	 * Get available languages
	 *
	 * @returns {string[]} Array of language codes
	 */
	getAvailableLanguages() {
		return Object.keys(translations);
	}
}

module.exports = I18n;
